### ISSUE TITLE
git:// protocol blocked here, can't get your kconfig

### ISSUE THREAD

**Issue by daveloyall** [gittup/gittup#14]
Since the port that the `git://` protocol uses is blocked here, I can't get your `kconfig` without using port forwarding or a proxy or whatever.

Please consider exposing your git repos via ssh or https.  Thank you!

**Comment by gittup** [comment]
I've pushed the kconfig repo to github as well now: https://github.com/gittup/kconfig

**Comment by daveloyall** [comment]
Thanks!
