### ISSUE TITLE
tup fails to save dependencies for exe on windows

### ISSUE THREAD

**Issue by marler8997** [gittup/gittup#9]
tup fails saying that is was unable to save dependencies after invoking a compiler on windows to create a .exe file.

On Windows (tup v0.7.3-18-g8e63ea4)
```
dir
    test.c
    Tupfile
```
test.c
----
```C
#include <stdio.h>
int main(int argc, char* argv[])
{
  printf("Hello, World\n");
  return 0;
}
```
Tupfile
----
```
: test.c |> cl /c test.c |> test.obj
: test.obj |> cl test.obj |> test.exe
```

```batch
REM run from Visual Studio Command prompt (to have the "cl" program in the path)
> tup init
> tup upd
[ tup ] [0.007s] Scanning filesystem...
[ tup ] [0.020s] Reading in new environment variables...
[ tup ] [0.030s] Parsing Tupfiles...
 1) [0.004s] .
 [ ] 100%
[ tup ] [0.039s] No files to delete.
[ tup ] [0.041s] Generating .gitignore files...
[ tup ] [0.049s] Executing Commands...
 1) [0.061s] cl /c test.c
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

test.c
* 2) cl test.obj
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Incremental Linker Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj
Unable to retrieve WOW64 info
 *** tup errors ***
tup error: Expected to write to file 'test.exe' from cmd 24 but didn't
 *** Command ID=24 ran successfully, but tup failed to save the dependencies.
 [  ] 100%
 *** tup: 1 job failed.
```

The `test.exe` program was created but tup still shows an error.  I just got started with tup so I don't know what's going on.  Is this a bug or am I doing something wrong?

**Comment by mathieujobin** [comment]
I think your clue is there... `Unable to retrieve WOW64 info`

does not look to be a problem with tup

**Comment by gittup** [comment]
The "Unable to retrieve WOW64 info" error message is from tup's dependency
checker. However, I am unable to reproduce the error with that version of
tup. My version of cl looks slightly newer though:

Microsoft (R) C/C++ Optimizing Compiler Version 18.00.21005.1 for x86

Any Windows experts know what might be going on here?

-Mike

**Comment by gittup** [comment]
Tracked in https://github.com/gittup/tup/issues/219
